    # mime_type    values = [                 dict( mt_name='application/msword', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/octet-stream', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/ogg', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/pdf', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/pgp-keys', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/pgp-signature', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/postscript', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/rar', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/rdf+xml', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/rss+xml', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.ms-excel', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.ms-powerpoint', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.chart', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.database', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.formula', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.graphics', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.graphics-template', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.image', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.presentation', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.presentation-template', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.spreadsheet', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.spreadsheet-template', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.text', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.text-master', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.text-template', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.oasis.opendocument.text-web', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.stardivision.calc', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.stardivision.draw', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.stardivision.impress', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.stardivision.math', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.stardivision.writer', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.stardivision.writer-global', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.calc', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.calc.template', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.draw', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.draw.template', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.impress', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.impress.template', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.math', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.writer', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.writer.global', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/vnd.sun.xml.writer.template', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-dvi', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-flac', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-font', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-freemind', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-gnumeric', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-gtar', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-java-jnlp-file', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-kpresenter', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-kspread', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-kword', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/xml', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-shockwave-flash', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/x-tar', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='application/zip', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/basic', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/midi', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/mpeg', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/mpegurl', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/x-aiff', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/x-mpegurl', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/x-ms-wma', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/x-pn-realaudio', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/x-realaudio', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='audio/x-wav', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='(desconhecido)', description='(tipo deconhecido)', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/gif', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/jpeg', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/png', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/svg+xml', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/tiff', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/vnd.djvu', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-coreldraw', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-coreldrawpattern', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-coreldrawtemplate', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-corelphotopaint', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-icon', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-ms-bmp', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-photoshop', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-portable-anymap', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-portable-bitmap', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-portable-graymap', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-portable-pixmap', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-rgb', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-xbitmap', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-xpixmap', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='image/x-xwindowdump', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='text/html', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='text/plain', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='text/richtext', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='text/rtf', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='video/mp4', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='video/mpeg', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='video/quicktime', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='video/x-ms-wmv', description='', edit_command='', view_command='', preferred_order=1 )
                dict( mt_name='video/x-sgi-movie', description='', edit_command='', view_command='', preferred_order=1 )
                

    # mime_type_ext    values = [                 dict( mime_type_id='8', extension='ai' )
                dict( mime_type_id='62', extension='aif' )
                dict( mime_type_id='62', extension='aifc' )
                dict( mime_type_id='62', extension='aiff' )
                dict( mime_type_id='90', extension='asc' )
                dict( mime_type_id='58', extension='au' )
                dict( mime_type_id='3', extension='bin' )
                dict( mime_type_id='79', extension='bmp' )
                dict( mime_type_id='74', extension='cdr' )
                dict( mime_type_id='76', extension='cdt' )
                dict( mime_type_id='77', extension='cpt' )
                dict( mime_type_id='90', extension='csv' )
                dict( mime_type_id='90', extension='diff' )
                dict( mime_type_id='73', extension='djv' )
                dict( mime_type_id='73', extension='djvu' )
                dict( mime_type_id='2', extension='doc' )
                dict( mime_type_id='2', extension='docx' )
                dict( mime_type_id='2', extension='dot' )
                dict( mime_type_id='46', extension='dvi' )
                dict( mime_type_id='8', extension='eps' )
                dict( mime_type_id='47', extension='flac' )
                dict( mime_type_id='68', extension='gif' )
                dict( mime_type_id='50', extension='gnumeric' )
                dict( mime_type_id='48', extension='gsf' )
                dict( mime_type_id='51', extension='gtar' )
                dict( mime_type_id='89', extension='htm' )
                dict( mime_type_id='89', extension='html' )
                dict( mime_type_id='78', extension='ico' )
                dict( mime_type_id='52', extension='jnlp' )
                dict( mime_type_id='69', extension='jpe' )
                dict( mime_type_id='69', extension='jpeg' )
                dict( mime_type_id='69', extension='jpg' )
                dict( mime_type_id='59', extension='kar' )
                dict( mime_type_id='6', extension='key' )
                dict( mime_type_id='53', extension='kpr' )
                dict( mime_type_id='53', extension='kpt' )
                dict( mime_type_id='54', extension='ksp' )
                dict( mime_type_id='55', extension='kwd' )
                dict( mime_type_id='55', extension='kwt' )
                dict( mime_type_id='63', extension='m3u' )
                dict( mime_type_id='60', extension='m4a' )
                dict( mime_type_id='59', extension='mid' )
                dict( mime_type_id='59', extension='midi' )
                dict( mime_type_id='49', extension='mm' )
                dict( mime_type_id='95', extension='mov' )
                dict( mime_type_id='97', extension='movie' )
                dict( mime_type_id='60', extension='mp2' )
                dict( mime_type_id='60', extension='mp3' )
                dict( mime_type_id='94', extension='mp4' )
                dict( mime_type_id='93', extension='mpe' )
                dict( mime_type_id='93', extension='mpeg' )
                dict( mime_type_id='60', extension='mpega' )
                dict( mime_type_id='93', extension='mpg' )
                dict( mime_type_id='60', extension='mpga' )
                dict( mime_type_id='17', extension='odb' )
                dict( mime_type_id='16', extension='odc' )
                dict( mime_type_id='18', extension='odf' )
                dict( mime_type_id='19', extension='odg' )
                dict( mime_type_id='21', extension='odi' )
                dict( mime_type_id='27', extension='odm' )
                dict( mime_type_id='22', extension='odp' )
                dict( mime_type_id='24', extension='ods' )
                dict( mime_type_id='26', extension='odt' )
                dict( mime_type_id='4', extension='ogg' )
                dict( mime_type_id='20', extension='otg' )
                dict( mime_type_id='29', extension='oth' )
                dict( mime_type_id='23', extension='otp' )
                dict( mime_type_id='25', extension='ots' )
                dict( mime_type_id='28', extension='ott' )
                dict( mime_type_id='75', extension='pat' )
                dict( mime_type_id='82', extension='pbm' )
                dict( mime_type_id='48', extension='pcf' )
                dict( mime_type_id='48', extension='pcf.Z' )
                dict( mime_type_id='5', extension='pdf' )
                dict( mime_type_id='48', extension='pfa' )
                dict( mime_type_id='48', extension='pfb' )
                dict( mime_type_id='83', extension='pgm' )
                dict( mime_type_id='7', extension='pgp' )
                dict( mime_type_id='70', extension='png' )
                dict( mime_type_id='81', extension='pnm' )
                dict( mime_type_id='90', extension='pot' )
                dict( mime_type_id='84', extension='ppm' )
                dict( mime_type_id='15', extension='pps' )
                dict( mime_type_id='15', extension='ppt' )
                dict( mime_type_id='8', extension='ps' )
                dict( mime_type_id='80', extension='psd' )
                dict( mime_type_id='95', extension='qt' )
                dict( mime_type_id='65', extension='ra' )
                dict( mime_type_id='65', extension='ram' )
                dict( mime_type_id='9', extension='rar' )
                dict( mime_type_id='10', extension='rdf' )
                dict( mime_type_id='85', extension='rgb' )
                dict( mime_type_id='65', extension='rm' )
                dict( mime_type_id='11', extension='rss' )
                dict( mime_type_id='92', extension='rtf' )
                dict( mime_type_id='91', extension='rtx' )
                dict( mime_type_id='31', extension='sda' )
                dict( mime_type_id='30', extension='sdc' )
                dict( mime_type_id='32', extension='sdd' )
                dict( mime_type_id='32', extension='sdp' )
                dict( mime_type_id='34', extension='sdw' )
                dict( mime_type_id='35', extension='sgl' )
                dict( mime_type_id='89', extension='shtml' )
                dict( mime_type_id='33', extension='smf' )
                dict( mime_type_id='58', extension='snd' )
                dict( mime_type_id='37', extension='stc' )
                dict( mime_type_id='39', extension='std' )
                dict( mime_type_id='41', extension='sti' )
                dict( mime_type_id='45', extension='stw' )
                dict( mime_type_id='71', extension='svg' )
                dict( mime_type_id='71', extension='svgz' )
                dict( mime_type_id='56', extension='swf' )
                dict( mime_type_id='56', extension='swfl' )
                dict( mime_type_id='36', extension='sxc' )
                dict( mime_type_id='38', extension='sxd' )
                dict( mime_type_id='44', extension='sxg' )
                dict( mime_type_id='40', extension='sxi' )
                dict( mime_type_id='42', extension='sxm' )
                dict( mime_type_id='43', extension='sxw' )
                dict( mime_type_id='57', extension='tar' )
                dict( mime_type_id='51', extension='taz' )
                dict( mime_type_id='90', extension='text' )
                dict( mime_type_id='51', extension='tgz' )
                dict( mime_type_id='72', extension='tif' )
                dict( mime_type_id='72', extension='tiff' )
                dict( mime_type_id='90', extension='txt' )
                dict( mime_type_id='34', extension='vor' )
                dict( mime_type_id='67', extension='wav' )
                dict( mime_type_id='64', extension='wma' )
                dict( mime_type_id='96', extension='wmv' )
                dict( mime_type_id='86', extension='xbm' )
                dict( mime_type_id='14', extension='xlb' )
                dict( mime_type_id='14', extension='xls' )
                dict( mime_type_id='14', extension='xlsx' )
                dict( mime_type_id='14', extension='xlt' )
                dict( mime_type_id='12', extension='xml' )
                dict( mime_type_id='87', extension='xpm' )
                dict( mime_type_id='12', extension='xsl' )
                dict( mime_type_id='88', extension='xwd' )
                dict( mime_type_id='13', extension='zip' )
                

