# -*- coding: utf-8 -*-
from m16e.kommon import KQV_PREFIX

KTF_MAX_SEL_REC_COUNT = 1000

#------------------------------------------------------------------
KTF_APPEND_ID = 'append_id'
# KTF_ARGS = 'args'
KTF_ACTION = 'action'
KTF_ACTIONS = 'actions'
KTF_AJAX_FIELD_CHANGED = 'ajax_field_changed'
KTF_AJAX_TARGET = 'ajax_target'
KTF_APPEND_ID = 'append_id'
KTF_ARGS = 'args_f'
KTF_ARGS_F = 'args_f'
KTF_ARGS_V = 'args_v'
KTF_BUTTON = 'button'
KTF_BUTTONS = 'buttons'
KTF_CALLBACK = 'callback'
KTF_COL_ORDER = 'col_order'
KTF_CELL_CLASS = 'cell_class'
KTF_CELL_IDS = 'cell_ids'
KTF_CELL_LINK = 'cell_link'
KTF_CSS_CLASS = 'css_class'
KTF_CHECKBOX = 'checkbox'
KTF_CHECKBOXES = 'checkboxes'
KTF_CHECKBOX_ID = 'checkbox_id'
KTF_COLS = 'cols'
KTF_COL_NAME = 'col_name'
KTF_COL_ORDER = 'col_order'
KTF_DECIMALS = 'decimals'
KTF_EDITABLE = 'editable'
KTF_EDITABLE_CLASS = 'editable_class'
KTF_FILTER_PANEL = 'filter_panel'
KTF_FLD_ID = 'fld_id'
KTF_GROUPBY = 'groupby'
KTF_HEADER_GROUPS = 'header_groups'
KTF_HEIGHT = 'height'
KTF_HIDE_ZEROS = 'hide_zeros'
KTF_ICON = 'icon'
KTF_ID = 'id'
KTF_IMG = 'img'
KTF_KEY = 'key'
KTF_KEY_LIST = 'key_list'
KTF_LIMIT = 'limit'
KTF_LINK_C = 'link_c'
KTF_LINK_F = 'link_f'
KTF_MASK = 'mask'
KTF_MAX_LENGTH = 'max_length'
KTF_MSG = 'msg'
KTF_MV_FIELD_ID = 'mv_field_id'
KTF_MV_INSERTION_POINTS = 'mv_insertion_points'
KTF_MV_INSERT_POINT = 'mv_insert_point'
KTF_MV_LINK_TABLE = 'mv_link_table'
KTF_NAME = 'name'
KTF_NULL = '<null>'
KTF_ONCLICK = 'onclick'
KTF_OPTIONS = 'options'
KTF_ORDER = 'order'
KTF_READONLY = 'readonly'
KTF_ROW_ID_MASK = 'row_id_mask'
# KTF_ROW_ID_FIELD = 'row_id_field'
KTF_ROW_CLASS = '_row_class'
KTF_ROW_DATA = 'row_data'
KTF_ROWS = 'rows'
KTF_SELECT = 'select' # equal to KTF_SELECT_INT
KTF_SELECT_INT = 'select_int'
KTF_SELECT_LIVE_SEARCH = 'select_live_search'
# KTF_SELECTED = 'selected' # dropped
KTF_SORTABLE_COLS = 'sortable_cols'
KTF_SPAN = 'span'
KTF_TABLE = 'table'
KTF_TARGET = 'target'
KTF_TEXT = 'text'
KTF_TITLE = 'title'
KTF_TOTALIZE = 'totalize'
KTF_TYPE = 'type'
KTF_USE_ICON = 'use_icon'
KTF_WIDTH = 'width'
KTF_VALUE = 'value'
# KTF_VARS = 'vars'
KTF_VARS = 'vars_f'
KTF_VARS_F = 'vars_f'
KTF_VARS_V = 'vars_v'

K_CHK_ID_PREFIX = 'chk_id_'

KQV_RETURN_NAME = KQV_PREFIX + 'return_name'

# #----------------------------------------------------------------------
# navigation
ACT_NAV_FIRST = 'act_nav_first'
ACT_NAV_LAST = 'act_nav_last'
ACT_NAV_NEXT = 'act_nav_next'
ACT_NAV_PREV = 'act_nav_prev'

